### ISSUE TITLE
UnicodeDecodeError when importing citeproc on Windows 10

### ISSUE THREAD

**Issue by rly** [brechtm/citeproc-py#106] opened 2020-12-03 08:00 UTC
Using version 0.5.1. When I open a Python 3.8 terminal and call `import citeproc` on Windows, I get:
```
Python 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import citeproc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Ryan\miniconda3\envs\test_due\lib\site-packages\citeproc\__init__.py", line 43, in <module>
    locales_json = json.load(file)
  File "C:\Users\Ryan\miniconda3\envs\test_due\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\Ryan\miniconda3\envs\test_due\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1266: character maps to <undefined>
```

This seems to be fixed by changing 
https://github.com/brechtm/citeproc-py/blob/7ebd0d6ab983d2632acc34916c25587c20e056f4/citeproc/__init__.py#L42
to 
`with open(os.path.join(LOCALES_PATH, 'locales.json'), encoding='utf-8') as file:`

**Comment by yarikoptic** [comment] 2020-12-03 14:26
Thank you @rly for digging this out!  I do not want to steal an opportunity from you to become a contributor -- interested to submit a PR with this change?

I think this is the same issue as #87 . We also need CI for windows and OSX, filed #107

**Comment by brechtm** [comment] 2020-12-03 15:17
> I think this is the same issue as #87

It has the same root cause: Python on Windows doesn't use ATF-8 as the default encoding. The suggested fix for this issue will not solve #87, however.

**Comment by sammy-w** [comment] 2021-01-19 08:55
The proposed solution: `with open(os.path.join(LOCALES_PATH, 'locales.json', encoding='utf-8')) as file:` at line 42 in init.py 
gives me an error because join does not take encoding as an input argument. 
I fixed it by puttting the encoding argument outside of the brackets
 `with open(os.path.join(LOCALES_PATH, 'locales.json') encoding='utf-8') as file:`

**Comment by rly** [comment] 2021-01-19 17:40
Thanks. I wrote this incorrectly in my original post and have edited the post to correct it. (It is written correctly, as you wrote, in PR #109.)

**Closed** 2021-01-19 19:42 UTC
Labels: windows
